/**
 *@Generated by QuickVO Tools 1.5 
 */
package com.lakala.elive.beans;


/**
 * @version 1.0.0
 * 投票选项表  		
 * VoteItemVO generated by biz_vote_item
 */
public class VoteItemInfo {
	
	/**
	 * 占比
	 */
	private String ratio;


    /**
     * 投票选项编号
     */
    protected String voteItem;

    /**
     * 任务编号
     */
    protected String voteId;

    /**
     * 选项名称
     */
    protected String itemName;

    /**
     * 得票数
     */
    protected Long voteCnt;

    //是否选择
    protected int isVote;


    public int getIsVote() {
        return isVote;
    }

    public void setIsVote(int isVote) {
        this.isVote = isVote;
    }

    public String getRatio() {
        return ratio;
    }

    public void setRatio(String ratio) {
        this.ratio = ratio;
    }

    public String getVoteItem() {
        return voteItem;
    }

    public void setVoteItem(String voteItem) {
        this.voteItem = voteItem;
    }

    public String getVoteId() {
        return voteId;
    }

    public void setVoteId(String voteId) {
        this.voteId = voteId;
    }

    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public Long getVoteCnt() {
        return voteCnt;
    }

    public void setVoteCnt(Long voteCnt) {
        this.voteCnt = voteCnt;
    }

    @Override
    public String toString() {
        return "VoteItemInfo{" +
                "ratio='" + ratio + '\'' +
                ", voteItem='" + voteItem + '\'' +
                ", voteId='" + voteId + '\'' +
                ", itemName='" + itemName + '\'' +
                ", voteCnt=" + voteCnt +
                '}';
    }
}
